In [1]:
import numpy as np
import pandas as pd

In [6]:
data = pd.read_csv("clean_weather.csv",index_col=0)
data = data.ffill()
data.head()


tmax  tmin  rain  tmax_tomorrow
1970-01-01  60.0  35.0   0.0           52.0
1970-01-02  52.0  39.0   0.0           52.0
1970-01-03  52.0  35.0   0.0           53.0
1970-01-04  53.0  36.0   0.0           52.0
1970-01-05  52.0  35.0   0.0           50.0

In [21]:
temps = data["tmax"].tail(3).to_numpy()
temps

array([66., 70., 62.])


### Forward Pass and Prediction

Let's go through an example to see how this works. We'll initialize each weight matrix, then perform a sample forward pass with 3 sequence elements:

1. **Input Weights (`i_weights`)**: These weights connect the input to the hidden layer.
2. **Hidden Weights (`h_weights`)**: These weights connect the hidden state from the previous time step to the current hidden state.
3. **Output Weights (`o_weights`)**: These weights connect the hidden layer to the output.

The forward pass involves calculating the following for each time step:
- **Input to Hidden (`XI_t`)**: The contribution of the input at the current time step to the hidden state.
- **Hidden State (`XH_t`)**: The combined effect of the input and the previous hidden state, passed through an activation function (ReLU in this case).
- **Output (`XO_t`)**: The prediction for the next sequence element, based on the current hidden state.

We perform this process for 3 sequence elements (`x0`, `x1`, `x2`) using the initialized weights and inputs.
```

In [22]:
# input
x0 = temps[0].reshape(1,1)
x1 = temps[1].reshape(1,1)
x2 = temps[2].reshape(1,1)

In [23]:
#weights
np.random.seed(0)
i_weights = np.random.rand(1,2)
h_weights = np.random.rand(2,2)
o_weights = np.random.rand(2,1)


In [ ]:
# calculate xi at time step 0
XI_0 = x0 @ i_weights
# there is no previous time step, so there is not going to be a hidden state
XH_0 = np.maximum(0, XI_0) # relu
# Output at time step 0 at xo_0
XO_0 = XH_0 @ o_weights
XO_0

array([[57.94406231]])

In [25]:
XI_1 = x1 @ i_weights
XH = XH_0 @ h_weights
XH_1 = np.maximum(0,XH+XI_1)
XO_1 = XH_1@ o_weights
XO_1

array([[124.54916092]])

In [26]:
XI_2 = x2 @ i_weights
XH = XH_1 @ h_weights
XH_2 = np.maximum(0,XH+XI_2)
XO_2 = XH_2@ o_weights
XO_2

array([[190.94853131]])

We've now passed through 3 forward steps of our RNN! The output x0 at each time step is the prediction for the next element in the sequence.

The hidden state of the RNN allows the network to have information about all past sequence elements. So when we're processing the sequence item at time step 2, the hidden state of the RNN stores information about the sequence elements at time step 0 and 1.